Sind diese Systemspezifikationen konsistent? (Beachten Sie, dass die im technischen Englisch gern verwendeten Begriffe „`q is necessary for p`“ und „`p only if q`“ Beschreibungen der Aussage p ⇒ q sind.)

a. The router can send packets to the edge system only if it supports the new address space.
b. For the router to support the new address space it is necessary that the latest software release be installed.
c. The router can send packets to the edge system if the latest software release is installed.
d. The router does not support the new address space.

==== Variables:

latexmath:[s]: **s**end packets

latexmath:[n]: supports **n**ew address space

latexmath:[r]: latest  **r**elease

==== Solution


|===
|s |n |r |latexmath:[s \rightarrow n] |latexmath:[n \rightarrow r] |latexmath:[s \cap r] |latexmath:[\neg n]

|0
|0
|0
|1
|1
|0
|1

|0
|0
|1
|1
|1
|0
|1

|0
|1
|0
|1
|0
|0
|0

|0
|1
|1
|1
|1
|0
|0

|1
|0
|0
|0
|1
|1
|1

|1
|0
|1
|0
|1
|0
|1

|1
|1
|0
|1
|0
|0
|0

|1
|1
|1
|1
|1
|1
|0

|===


ist nicht konsistent

