Beurteilen Sie, ob die folgenden Sätze und Formeln Aussagen oder Aussageformen sind. Geben Sie (so
möglich) den Wahrheitswert an.

==== A~1~ : latexmath:[n^2 = 4]

Aussage
false für latexmath:[x \neq 2]

==== A~2~ : latexmath:[\exists_{n \in \mathbb{N}} n^2 = 4]


true, da mit n=2 ein Element in den natürlichen Zahlen existiert, das zum Quadrat 4 ergibt

==== A~3~ : latexmath:[\forall_{n \in \mathbb{N}} n^2 = 4]
false, da nicht alle elemente quadriert 4 ergeben. Beispiel: latexmath:[1^2 = 1]

==== B~1~ : Alle Filme werden in Hollywood produziert.

false, Laut Wikipedia hat nur eines der 5 größten Filmstudios noch in Los Angeles seinen Sitz. Siehe: https://en.wikipedia.org/wiki/Paramount_Pictures.
Als Gegenbeispiel von Filmen seien Samurai Filme genannt die größtenteils in Japan produziert werden.

==== B~2~ : Es gibt Filme, die in Hollywood produziert werden.

true, da "The Godfather" und "The Godfatehr II" in Hollywood produziert wurde.

==== B~3~ : Ein Film wurde in Hollywood produziert.

true, da "The Godfather" in Hollywood produziert wurde.

==== B~3~ : „Matrix“ wurde in Hollywood produziert.

false, Matrix wurde in Sydney gefilmt.
